### ISSUE TITLE
Not compatible with strict CSP due to `new Function(..)`

### ISSUE THREAD

**Issue by harriha** [jquense/expr#1]
Hi,

I'm using react-formal with yup, and while hardening my app's CSP rules to drop `unsafe-eval` ([reference](https://www.w3.org/TR/2015/CR-CSP2-20150721/#directive-script-src)), I'm seeing explosions because this library [uses](https://github.com/jquense/expr/blob/master/index.js#L21) `new Function(...)` which isn't allowed with that kind of CSP setup.

Any chance doing something else here instead, to make this compatible with stricter CSP rules (which are assumably becoming more common)? 

Currently I'm not seeing good ways around this in my end, seems that I need to choose between dropping react-formal and yup or to live with `unsafe-eval` in CSP (and justify that to the party evaluating the security of my app).

**Comment by novemberborn** [comment]
Per https://github.com/jquense/yup/issues/135#issuecomment-337633638:

>  If you want to put something together there with a similar perf profile I'd be happy to take a look

Somebody would need to change this package so it doesn't use `new Function`. Performance is a concern though.

Unfortunately I'm leaving the project that led me to this issue tomorrow, so I won't have the time myself to work on this. I'll be sure to let my client's devs know about this though 😄

**Comment by maxmalov** [comment]
Is there any reason to not use lodash.get/lodash.set packages?

**Comment by AndyTyurin** [comment]
Hey guys, I had stuck with same problem of CSP.
As I'm using Yup as validation schema for Formik and we need to find solution for this issue too.
Any ideas?

**Comment by AndyTyurin** [comment]
> Is there any reason to not use lodash.get/lodash.set packages?
`expr` provides already calculated cached functions for retrieving values from object passing to, which should be performant against `lodash.get/set`.
But of course if CSP not works there is no need to use `yup` at all.

I would like to make PR to change behavior, it will be less performant, but should be better then lodash. Also gives opportunity to use formik/yup/expr in highly-secured apps with CSP eval.

**Comment by maxmalov** [comment]
@dinobhai I've ended up using https://github.com/ds300/patch-package to patch `yup` locally to use `get/set` from lodash.

**Comment by belgac** [comment]
This workaround gives me other problems, if the contentSecurityPolicy variable is set to true (either manually to test the problem by hardcoding it or by the try catch on a site that has a csp) the following validation doesn't work anymore in yup

`Yup
  .string()
  .required('required')
  .oneOf([Yup.ref('ref'), null], 'passwordMismatch');`

I'm looking to understand why but other users might be impacted

**Comment by d4nwils0n-rm** [comment]
Hi,
I am using Formik with Yup too and I still seem to get CSP violations, from what I can see the try/catch calls `new Function('')` which still fires a CSP violation for me. Does anyone know of any other ways to check to see if a content security policy exists? Or does anyone have any other ideas on how to fix this?

**Comment by paulwalczewski** [comment]
@d4nwils0n-rm, you are right, CSP error is still being thrown in console, but for some reason it is happening only in Firefox...
Perhaps all other browsers detect when eval/new Function('') is defined in try/catch and silently go to catch block instead of warning of CSP being violated? Or perhaps they don't put function constructor in CSP - eval policy yet?

@belgac, according to:
[](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/CSP#Applicable_CSP_Restrictions)

both eval and function constructor are now banned.
Having that in mind, wouldn't it be better to set current fallback version as a default one?
You could still keep the high-performance, constructor based one, but that could be used only when user chooses too. For example by setting up env variables on compile time:

```
if (process.env.NODE_ENV === 'production') {
  contentSecurityPolicy = true // your current flag to use fallback
} else {
  ... current try / catch check to use new Function if it is accessible
}
```

**Comment by jquense** [comment]
happy to take a PR adding a manual toggle in addition to the detection, tho we should see if we can make detection work. AFAIK we are also using CSP and aren't hitting issues in FF

**Comment by paulwalczewski** [comment]
Hi @jquense, I've created a PR: https://github.com/jquense/expr/pull/10

**Comment by jquense** [comment]
v2 no longer uses `new Function` by default
