### ISSUE TITLE
Failed to compile issue

### ISSUE THREAD

**Issue by anaekin** [jquense/expr#13]
Getting Failed to compile during npm run build in my react app because of line 55 in index.js. I cannot use react-scripts as I am using a custom script. Suggested change - use of 'var' instead of 'let'.

**Comment by jquense** [comment]
happy to take a PR fixing it!

**Comment by vijayshukla30** [comment]
Same issue any luck

**Comment by anaekin** [comment]
Already fixed and @jquense accepted the merge request.

**Comment by anaekin** [comment]
> Already fixed and @jquense accepted the merge request.

I suppose @jquense may require to publish the new version with these changes.

**Comment by jquense** [comment]
released
